### ISSUE TITLE
hatalar.db

### ISSUE THREAD

**Issue by ttbilgin** [ttbilgin/PyNar_HataKontrol#1]
Mustafa veritabanı istediğim şekilde olmuş fakat birkaç noktada düzeltme gerekli.

Şu an veritabanından alına hatanın türkçesi değil hala ingilizcesi yazıyor.

Database Design dersini sanırım henüz almadın.
1) Tablo adlarında türkçe büyük İ harfi var, bunu düzeltirsen iyi olur.
2) her bir tabloda mutlaka Primary Key olur bu da genelde auto increment olur. Aksi durumda Aynı hata kodu birden fazla satırda varsa sorgulamak sıkıntılı olur.

![mustafa](https://user-images.githubusercontent.com/854154/100275727-72470900-2f71-11eb-8175-23e5dae9ca5d.PNG)

**Comment by Onefivezero** [comment]
ID adlı 1 2 3 4 auto increment primary key eklendi. Gerekirse HATA_KODU primary key yapılabilir.
